export const TOOL_TIP_INFO = {
  orgCode : 'Enter your organization unit code based on the coding structure you are using. You can enter group company code, corporate unit code, corporate departments, SBU code, or SBU department code',
  year : 'Year is a required to find the organization strategic analysis for the particular year.',
  version: 'Version is important to find variations of Analysis in one year.',
  typeOfUnit: 'Select the organization unit type from drop down like Group Company, corporate unit, SBU, Corporate department, SBU department',
  kpiCode: 'Enter KPI code based on coding structure.',
  kpiPolarity: 'Polarity is an indicator of measure. Whether our desired values/target is high or low on a scale.',
  dataSource: 'Enter from where the KPI data comes.',
  dataQuality: 'Data',
  scCode: 'Select Scorecard Code, you can see list of scorecards which are generated in Scorecard Screen.',
  scName: 'Enter Scorecard Code based on your coding structure.',
  objCode: 'Enter Objective Code based on your coding Structure. Which are helps to achieve your organization vision.',
  themeName: 'Select Theme to bind group of objectives into one Theme.',
  perspectiveCode: 'Enter Perspective Code based on your coding Structure. To convert your organization strategy into execution',
  perspectiveName: 'Name the perspective in which way the strategic plan looking on your organization',
  initiativeCode: 'Enter initiative code based on coding structure you are using',
  fromDate: 'Select from date of your initiative/Project from calendar',
  toDate: 'Select to date of your initiative/Project from calendar',
  budget: 'Enter estimated budget of the project',
  thCode: 'Enter theme Code based on your coding Structure.',
  thName: 'Enter theme Name based on your coding Structure.',
  deptCode: 'Department Code',
  empId: 'Enter Employee ID',
  empTitle: 'Enter Employee Title',
  milestoneCode: 'Enter milestone code to maintain phases of a Project/Initiative.',
  themeCode: 'Enter Theme Code'
};
